### ISSUE TITLE
Security warning email for elasticsearch docker

### ISSUE THREAD

**Issue by kootenpv** [deviantony/docker-elk#116]
I just got a security warning that the elasticsearch docker (without any edits) as part of this stack is unsecured.

Is there a way to make it only listen on localhost?

What is the way to configure authentication in the docker-compose file, or should that be done differently?

**Comment by antoineco** [comment]
If you're running it on Linux the best thing to do is to remove the port mappings from the compose file, since you can access each applications on their respective container IP directly.

If you're running it using Docker for Mac you probably want to map ports on your loopback, as described here: https://docs.docker.com/compose/compose-file/#ports

**Comment by kootenpv** [comment]
Thanks a lot @antoineco. That sounds like a very good solution. I can access it.

For others, you can find the container ip like this:

    docker inspect b5c45acd6bb8 | grep IPAddress
