### ISSUE TITLE
Replacing Logstash with fluentd

### ISSUE THREAD

**Issue by blackholegalaxy** [deviantony/docker-elk#135]
Hi there, 

I know it's not the main purpose of ELK stack, but i'm trying to replace logstash by Fluentd. Any of you has managed or tried to use fluentd with similar configuration you used there?

I can't find any good resource about doing so.

Thanks for your help on that.

**Comment by antoineco** [comment]
@blackholegalaxy that's a good question, a bit off-topic but since I've used such a setup myself for testing purposes I'll try to give you some pointers.

In case you haven't seen it already, Fluentd has an [official Docker image](https://hub.docker.com/r/fluent/fluentd/) with an example of how to install the fluentd plugin for Elasticsearch in a Dockerfile.  You could start by replacing the provided Dockerfile for logstash by one of the examples found on that page.

Then add something like this to your fluentd configuration (which you can [mount from your host](https://github.com/deviantony/docker-elk/blob/586302bf4e43a474ab7dbbbcafbd033f2b150589/docker-compose.yml#L20)):

```xml
<match my.logs>
  @type elasticsearch
  host elasticsearch
  port 9200
  index_name fluentd
  type_name fluentd
</match>
```
([source](https://github.com/uken/fluent-plugin-elasticsearch#usage))

**Comment by blackholegalaxy** [comment]
Thanks about that. It helps :)

**Comment by antoineco** [comment]
Sweet! Feel free to close the issue if you managed to make it work, otherwise I'll just leave it open for a couple more days.
