### ISSUE TITLE
file input plugin is not working

### ISSUE THREAD

**Issue by ibrahimsharaf** [deviantony/docker-elk#155]
Hello everyone, I am trying to use file input plugin instead of tcp, but it doesn't work (there are no injected files), here's a minimal configuration for logstash:

```
input {
    file {
        path => ["/home/ibrahimsharaf/docker-elk/logs/**/*.log"]
        codec => multiline {
            pattern => "^%{TIMESTAMP_ISO8601} "
            negate => true
            what => previous
        }
        sincedb_path => "/dev/null"
        start_position => "beginning"
    }
}

output {
		stdout {
			codec => rubydebug
		}
		elasticsearch {
			hosts => "elasticsearch:9200"
		}
}
```

**Comment by antoineco** [comment]
Maybe this question would be a better fit for the Elastic user community?

**Comment by ibrahimsharaf** [comment]
I thought it's a problem in communicating with docker-elk without TCP

**Comment by antoineco** [comment]
In this case please be more specific. "it doesn't work" without any error message is the best way to get no answer.

Are you trying to feed files which are not mounted inside the Logstash container? If that's the case, it sounds like the source of the problem is a misunderstanding of how Docker works, not something this project is accountable for, but maybe I misunderstood the issue myself.

**Comment by ibrahimsharaf** [comment]
> Are you trying to feed files which are not mounted inside the Logstash container?
I believe this is the source of the problem yes, I am new to docker, some concepts of volumes are quite confusing to me, can you point me on how to edit the docker-compose.yml to "mount" my files?

**Comment by antoineco** [comment]
I believe the general answer to that would be "the Docker documentation", but actually the README itself has some examples (for example "how to persist ES data").

In your case `/home/ibrahimsharaf/docker-elk/logs` doesn't exist within the container because it's not mounted (containers have their own isolated filesystem).
If you want to mount exactly this path, you have to add something like this to your compose file:

```
volumes:
  - /home/ibrahimsharaf/docker-elk/logs:/logs
```

and then use the path `/logs/**/*.log` inside your config file.

**Comment by ibrahimsharaf** [comment]
Thanks for help @antoineco, that was beneficial, closing issue.
