### ISSUE TITLE
Any way to get access to Linux logs?

### ISSUE THREAD

**Issue by ramalo** [deviantony/docker-elk#184]
Hi again ^^

I am tryting to learn how to use ELK to get information from the logs "auth.log" and "syslog". In many virtual machines I have found these logs in the "\var\logs" paths, but I cant find them in the docker-machine where I did "docker-compose up". 
Are these logs in any other path? Are these logs disable (so I have to enable them)? Do I have to install any plugin or something in order to get them autogenerated?

Thanks for the help ^^

**Comment by antoineco** [comment]
In a container you usually run a single process, not the full OS, so there is no logging facility. All logs are generated by the app you're running, and go to standard output so that Docker can collect them.

In some occasions, if the app is configured to do so, some logs are written on the filesystem but this is highly app specific. As far as I know none of the ELK components write to the filesystem by default.

you can run `docker-compose exec logstash ls` to check whether or not Logstash (for example) creates a log.

**Comment by antoineco** [comment]
@ramalo I'm gonna go ahead and close this, but feel free to use the Gitter channel if you want to discuss further.
