### ISSUE TITLE
How to change default password for searchguard?

### ISSUE THREAD

**Issue by loga4** [deviantony/docker-elk#226]
How to change default password for searchguard, if container was build already?

**Comment by antoineco** [comment]
@loga4 check this out: [Configuring the Internal Users Database](http://docs.search-guard.com/latest/internal-users-database) (especially the first link regarding the Kibana UI).

You probably want to [disable the `readonly` flag](https://github.com/deviantony/docker-elk/blob/95e6dae/elasticsearch/config/sg/sg_internal_users.yml#L6) on internal users first.

**Comment by loga4** [comment]
Thank you :)
Some steps to change default credentials:
1. Change password in `elasticsearch/config/sg/sg_internal_users.yml`
2. Change password for `logstash/pipeline/logstash.conf`
3. Rebuild images `docker-compose build`

**Comment by antoineco** [comment]
:ok: feel free to close this issue if your question was answered ;)

**Comment by kahara** [comment]
Is there a recommended way to set passwords to something else than non-default when bringing the containers up? *Before* they're up and listening on their ports.

What I would like to do is something like: supply the (plaintext) passwords as environment variables when saying `docker-compose up`, then have those passwords automagically hashed and corresponding entries created in `config/sg/sg_internal_users.yml`.

If there isn't a ready-made way to achieve this, any advice is appreciated before I start rolling my own solution.

**Comment by antoineco** [comment]
@kahara not that I know, but maybe some expert would be able to point you in the right direction @ https://groups.google.com/forum/#!forum/search-guard

**Comment by cgonzalez** [comment]
Is it possible to change default credentials without "docker-compose build"? I've tried every sgadmin.sh combination possible with zero results. Should I rebuild all the images and loss all my dashboards and searches every time I change a password in sg_internal_users.yml?

**Comment by antoineco** [comment]
@cgonzalez you could mount `config/sg/` as a volume inside `docker-compose.yml` and just run `docker-compose exec -T elasticsearch bin/init_sg.sh` again whenever you update a file.

Note: rebuilding images does not destroy data.

**Comment by antoineco** [comment]
@shijunti19 there is a link to a whole official guide in the first comment to this issue.

**Comment by shijunti19** [comment]
@antoineco  
1.Get a new password ：plugins/search-guard-6/tools/hasher.sh -p mycleartextpassword  
2.Modify account password
3.Change password in elasticsearch/config/sg/sg_internal_users.yml
4.Change password for logstash/pipeline/logstash.conf
5.docker-compose exec -T elasticsearch bin/init_sg.sh
6.Rebuild images docker-compose build
7.docker-compose down
8.docker-compose up -d
9.http://localhost:5601 and http://localhost:9200
Log in with a new password
Is that the way to do it？

I hope there are operations in the tutorial, because new people will not modify the password, and may be intruded by hackers.
A massive invasion of mongodb
