### ISSUE TITLE
Install plugins from local directory

### ISSUE THREAD

**Issue by Sneijky** [deviantony/docker-elk#287]
Hello,

I'm developing a kibana plugin and I have installed it in my kibana from a local directory using: .\bin\kibana-plugin install file:///path_to_file. Now I would like to add it a docker container using this repo.

So far I've tried to make a folder in the dockerfolder/kibana called plugins and added my plugin there but it didn't work.

I saw the documentation on how to add a kibana plugin but saw no reference to local file, is there anyway to install the plugin in the container using a file? 
 
Thanks.

**Comment by antoineco** [comment]
> I saw the documentation on how to add a kibana plugin but saw no reference to local file

Because plugins are installed at *build time* and not at run time, you must copy the sources of your plugins *before* calling `kibana-plugin`.

Add the following instructions to your Dockerfile:

```dockerfile
COPY  kibana/plugins /my_plugins
RUN   kibana-plugin install file:///my_plugins/plugin.zip
```

The syntax for the `kibana-plugin`  utility (including the usage of `file`) is documented here:
 * [Kibana User Guide [6.3] » Kibana Plugins » Installing Plugins](https://www.elastic.co/guide/en/kibana/current/install-plugin.html#_installing_plugins_to_an_arbitrary_directory).

**Comment by Sneijky** [comment]
> COPY  kibana/plugins /my_plugins
RUN   kibana-plugin install file:///my_plugins/plugin.zip

I added that to my Dockerfile and got the following error:

```
Step 2/3 : COPY  kibana/plugins /my_plugins
ERROR: Service 'kibana' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder562147717/kibana/plugins: no such file or directory
```

**Comment by antoineco** [comment]
Adapt the paths to your environment obviously.
