### ISSUE TITLE
Consider update X-Pack branch to 6.4.0 version?

### ISSUE THREAD

**Issue by metju312** [deviantony/docker-elk#317]
As in title: Do you consider update X-Pack branch to 6.4.0 version?
6.4.0 version of elasticsearch ensure **free** X-Pack futures like security.

**Comment by javmain** [comment]
Yes,😀😀

**Comment by metju312** [comment]
Great :) May I ask when?

**Comment by antoineco** [comment]
Done in 773e84cab829711af715029ca6f9e17a8260578f

**Comment by metju312** [comment]
What about information in README: "The trial [X-Pack] license is valid for 30 days."? Is this true or [elasticsearch producent info](https://www.elastic.co/products/x-pack/open) is wrong?

**Comment by antoineco** [comment]
@metju312 it is still true (see [elasticsearch.yml](https://github.com/deviantony/docker-elk/blob/773e84c/elasticsearch/config/elasticsearch.yml#L21)) because we are enabling security features, which are not available with a `basic` license.

It's the responsibility of the user to opt-out, otherwise the security features are automatically disabled after 30 days.

**Comment by metju312** [comment]
@antoineco u right, thanks a lot for answers :)
