### ISSUE TITLE
Need help to enable curator.

### ISSUE THREAD

**Issue by vcarette** [deviantony/docker-elk#353]
### Problem description

Hello,

I'm trying to enable curator on my docker-elk on centos 7 but when I launch the command `docker-compose -f docker-compose.yml -f extensions/curator/curator-compose.yml up`
I have the error `curator_1        | crond: user root: parse error at /usr/bin/curator`

ELK seems to work despite this because it still receives and displays logs.

I noticed that the `/usr/bin/curator` does not exist at the moment on the host, I don't know if that's normal.

I'm new to both Docker and ELK so I'm sorry if it's not the right place to ask this.

#### Stack configuration

I changed the paths in the `curator-compose.yml` to fit my system.

I created a file `/etc/cron.d/root` and replaced in the entrypoint.sh in place of `/etc/crontabs/root` but without success.

I also diabled Selinux.

#### Docker setup

```
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:35:01 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:06:30 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```
```
docker-compose version 1.23.2, build 1110ad0
docker-py version: 3.7.0
CPython version: 2.7.5
OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017
```

**Comment by antoineco** [comment]
> I noticed that the /usr/bin/curator does not exist at the moment on the host

`/usr/bin/curator` is inside the container, not on the host. Containers are isolated from the host file system.

> I changed the paths in the curator-compose.yml to fit my system.

> I created a file /etc/cron.d/root

Both of these are wrong for the reasons explained above. You can't change paths because all files reside inside the container, not on your host. You have to mount or `COPY` all files if you want to use different paths, and all files you mount must be relative to the `docker-elk` repo. I highly recommend to use the [default directory](https://github.com/deviantony/docker-elk/tree/master/extensions/curator/config) if you're new to Docker in order to avoid confusion.

> parse error

Means the content of your configuration file is invalid. Most likely the configuration file can not be found because of the paths you changed.

You can run `git checkout extensions/curator/` inside the repo in order to revert the configuration files to their default.

**Comment by vcarette** [comment]
Thanks for your explanations, it works now! It was indeed invalid configuration files.
