### ISSUE TITLE
Make it easier to switch between configuration "flavours"

### ISSUE THREAD

**Issue by deviantony** [deviantony/docker-elk#378]
Following the discussion started in https://github.com/deviantony/docker-elk/pull/360

Based on that discussion, we've identifier the following potential configurations that we can leverage using this project:

* PAID_TRIAL

Using the official Elastic **non open-source** images with all paid features enabled.

* FREE

Using the official Elastic **non open-source** images with all paid features disabled.

* OSS

Using the official Elastic **open-source** images.

* FREE+SEARCHGUARD

Using the official Elastic **non open-source** images as well as the elasticsearch plugin searchguard.

* OSS+SEARCHGUARD 

Using the official Elastic **open-source** images as well as the elasticsearch plugin searchguard.

Right now this project is using a mix of git branches, ENV flags/toggles as well as commented configuration sections to enable/disable a specific configuration.

We're looking for solutions to make this project easier to maintain (branch management is a pain even for minor contributions such as version upgrades).

Taken from the discussion:
> can we simplify it to support all these kinds of deployments inside a single branch instead of having to maintain and support multiple branches?

E.g. can we provide a way for the user to use FREE+SEARCHGUARD, or PAID_TRIAL or FREE after cloning the repo?

Secondly, think about replacing the default configuration from `OSS` to `PAID_TRIAL` for the reasons stated in https://github.com/deviantony/docker-elk/pull/360#issuecomment-480067051

cc @antoineco, do you have any thoughts on this matter?

**Comment by antoineco** [comment]
I also think it would make things easier if we could get rid of the extra `x-pack` branch, since X-Pack is now included by default with the Elastic stack. We don't redistribute the software, so the question of the Apache versus Elastic license is not an issue.

I don't have a strong opinion regarding whether the default should be to have paid features enabled or disabled. Slightly favoring the "free by default" perspective, but in both cases it's easy enough to have a documented option in the configuration file that allows the user to opt in/out.

Search Guard is a bigger integration that requires its own configuration, certificates, etc. It's a nice free alternative to X-Pack security that can also integrate with other X-Pack features to some extent. If we don't want to keep maintaining that branch, we could maybe send a PR to the devs so that they can use the current setup in order to provide a similar out-of-the-box experience?

**Comment by mw-jko** [comment]
Some c&p from the related PR to gather information in one place:

The whole question came on the table when I realized that elastic does not offer the (major version) upgrade wizard for the oss version anymore and I tried to find a way to solve both issues (provide a easy way to support both oss and "basic" AND configure xpack as easy as possible) and realized I have no clue how to do this: 

The problem with oss versus basic is: elastic crashes when one tries to configure features which are not included (like when trying to disable security in OSS image). This makes the `-oss` toggle (#360 ) error-prone. In case you want to use the "normal" (non oss) version, you have to set the flavour in the .env file *and* add lines to both kibana and elasticsearch yaml files.

> * PAID_TRIAL (default mode)
> * FREE
> * OSS
> * FREE+SEARCHGUARD
> * OSS+SEARCHGUARD (if supported by searchguard)

How do you define "default mode"? What's included in `master`? Or set `x-pack` as the default branch? (Not sure if this is possible in GitHub but I guess so) I would not change the "definition" of an branch, though. If one relies on the master branch we should not change this branch to the the paid trial. "Redefining" an existing branch always sucks (IMHO).

Otherwise sounds good to me, but I think it's increasing the required maintenance effort quite a lot when handling this over branches. When elastic changes things you have to adjust 5 branches, when searchguard changes things still 2. 

What about this: 

* all branches are changed to non `-oss` 
* `master` and `searchguard` have paid features disabled
* we add comments in the yml files and adjust the readme what to do to switch to pure `oss` (like: "set the flavour, remove/comment this and that lines in this and that files")

The problem is we have to decide over an trade-off. Increased maintenance effort but easy setup, or reduced maintenance effort, but more complicated/error-prone setup. 

Or we find a way to allow easier on/off handling, but I can't think of a possible solution for this atm.

**Comment by deviantony** [comment]
ping @floragunncom as they might be interested by this discussion as well.

> The problem is we have to decide over an trade-off. Increased maintenance effort but easy setup, or reduced maintenance effort, but more complicated/error-prone setup.

I'd definitely favor easy setup over increased maintenanced.

**Comment by mw-jko** [comment]
> I'd definitely favor easy setup over increased maintenanced.

Me too. At least basic version updates can be cherry-picked.

**Comment by floragunncom** [comment]
@deviantony @antoineco How can we help?

It's also the question what the main purpose of this repository is? Easy OOTB experience for testing/demoing/experimenting or groundwork/template for going into production?

> Search Guard is a bigger integration that requires its own configuration, certificates, etc. It's a nice free alternative to X-Pack security that can also integrate with other X-Pack features to some extent. If we don't want to keep maintaining that branch, we could maybe send a PR to the devs so that they can use the current setup in order to provide a similar out-of-the-box experience?

Maybe we can simplify the Search Guard setup here by using the demo installer? See https://docs.search-guard.com/latest/demo-installer#demo-installer and https://github.com/floragunncom/search-guard-helm/blob/master/docker/elasticsearch/Dockerfile but thats not for proudction of course.

**Comment by deviantony** [comment]
Seems like we might need to consider another flavour being `PAID_TRIAL` + `SEARCHGUARD`:

https://github.com/deviantony/docker-elk/pull/380

**Comment by antoineco** [comment]
@floragunncom easy OOTB experience for testing/demoing/experimenting is indeed the main purpose of this repo.

I see you have a similar setup for Kubernetes, but not for plain Compose right? (maybe I overlooked)
In this case I agree with @deviantony, we could keep the current `searchguard` branch and just switch to the X-Pack base image.

@deviantony does "paid trial" really apply when paid features are explicitly disabled?

**Comment by mw-jko** [comment]
> 
> 
> Seems like we might need to consider another flavour being `PAID_TRIAL` + `SEARCHGUARD`:
> 
> #380

I wonder if this is really required? Why use the elastic gold/platinum subscription and another 3rd party solution on top of that?

**Comment by mw-jko** [comment]
So how do we continue here? Do we have an agreement?

**Comment by deviantony** [comment]
What about the following steps ?

* Drop support for the `x-pack` and the `vagrant` branches
* Use non OSS version of images by default in `master` and `searchguard` branches and only maintain these 2 branches
* Document how to enable a pure OSS Elastic stack inside a specific section of the Readme 

Now regarding that point:

* `master` and `searchguard` have paid features disabled

I'm not sure whether this is the good way to go, as we stated this earlier in this discussion:

> easy OOTB experience for testing/demoing/experimenting is indeed the main purpose of this repo.

So in my opinion all paid features should be enabled **by default** to give a better understanding of what the Elastic stack can actually offer. Open to any thoughts on this topic.

**Comment by antoineco** [comment]
Also makes sense, as long as we mention how to opt out.

**Comment by mw-jko** [comment]
Fine to me as well. `searchguard` must have security disabled for obvious reasons, but that's not much of  a problem.

> Also makes sense, as long as we mention how to opt out.

Yep, in two steps: how/where to disable paid features, and how/where to switch to oss version. But I'm sure this can be handled with some lines in the readme :)

**Comment by ideascape** [comment]
Random comment from someone who actively uses docker-elk: perhaps the searchguard branch should have paid features disabled by default. It seems likely that someone using the searchguard branch probably won't be planning to use paid features. At least that's the case for my organization. Master could have paid features enabled by default (including xpack security).

**Comment by antoineco** [comment]
@ideascape thanks for the feedback, much appreciated! I sent a pull request with a proposal (see above this comment). There is a new section in the README that informs the user how to disable paid features (it's a single option). Feel free to comment on the PR!
