### ISSUE TITLE
Outdated search-gurad plugin link

### ISSUE THREAD

**Issue by obeyda** [deviantony/docker-elk#453]
i am having the following error when building the images: 

```
 ---> Running in 599361b6af97
Attempting to transfer from https://repo1.maven.org/maven2/com/floragunn/search-guard-kibana-plugin/7.4.1-36.2.0/search-guard-kibana-plugin-7.4.1-36.2.0.zip
Attempting to transfer from https://artifacts.elastic.co/downloads/kibana-plugins/https://repo1.maven.org/maven2/com/floragunn/search-guard-kibana-plugin/7.4.1-36.2.0/search-guard-kibana-plugin-7.4.1-36.2.0.zip/https://repo1.maven.org/maven2/com/floragunn/search-guard-kibana-plugin/7.4.1-36.2.0/search-guard-kibana-plugin-7.4.1-36.2.0.zip-7.4.1.zip
Plugin installation was unsuccessful due to error "No valid url specified."
ERROR: Service 'kibana' failed to build: The command '/bin/sh -c kibana-plugin install https://repo1.maven.org/maven2/com/floragunn/search-guard-kibana-plugin/${ELK_VERSION}-${SG_VERSION_KIBANA}/search-guard-kibana-plugin-${ELK_VERSION}-${SG_VERSION_KIBANA}.zip' returned a non-zero code: 70
```

the error is on this line:
https://github.com/deviantony/docker-elk/blob/6f97958f1c76095271165ef7b26e989f38db2f93/kibana/Dockerfile#L9

the url should be something like 
```https://releases.floragunn.com/search-guard-kibana-plugin/7.4.1-36.2.0/search-guard-kibana-plugin-7.4.1-36.2.0.zip```

**Comment by antoineco** [comment]
The URL is valid, but Floragunn is currently [in a legal battle with Elastic](https://github.com/deviantony/docker-elk/issues/433#issuecomment-534312828) over a DMCA.

The change you suggest was already done in 954d314be1ae6a3b376ba758b820dd9229d75049, then reverted in 8257b08a4cf13f266d8e879e24de9ee92731fb85 because Search Guard was made [available again on Maven](https://search.maven.org/search?q=g:com.floragunn%20AND%20a:search-guard-7&core=gav). However it seems like all artifacts have been blocked ([example](https://search.maven.org/remotecontent?filepath=com/floragunn/search-guard-kibana-plugin/7.4.1-36.2.0/search-guard-kibana-plugin-7.4.1-36.2.0.zip)), so it  seems like we don't have any other option but to revert again.

Thanks for reporting 👍

**Comment by antoineco** [comment]
Tests are [running](https://travis-ci.org/deviantony/docker-elk/builds/620156279). I'll merge the change as soon as everything passes.
