### ISSUE TITLE
Is ELK cpu/memory/storage consuming?

### ISSUE THREAD

**Issue by ruixue8080** [deviantony/docker-elk#501]
### Problem description

Our project has requirement for log aggregation of different micro-services, and ELK is great tool to do that. However our project has requirement of privatization deployment, which means we need to deploy the whole solution into customers' own servers. Based on this video(https://www.youtube.com/watch?v=cC4GGJ0JsSE), ELK has pre-requisites of at least 2GB RAM and at least 20GB storage, is this always the situation? If yes, then ELK is a little resource consuming, which may not quite fit to our privatization deployment situation. Create this issue and would like to get advise and suggestion about whether I should choose ELK for privatization deployment scenario for log aggregation.

**Comment by antoineco** [comment]
@ruixue8080 the short answer is: it depends on your needs, and only someone with familiarity with _your_ project can answer that.

---

I am closing this question because it has no relation with this project. I kindly recommend those places to ask general questions about Elasticsearch, they are full of experts:
* https://www.elastic.co/guide/index.html
* https://discuss.elastic.co/
* https://stackoverflow.com/questions/tagged/elasticsearch

> Because we focus purely on integrating the Elastic stack using Docker and not on the individual stack components themselves, we kindly ask our users to submit questions about Elastic products in the Elastic Discussion Forums @ https://discuss.elastic.co/.
>
> -- https://github.com/deviantony/docker-elk/blame/master/.github/ISSUE_TEMPLATE.md#L2
