### ISSUE TITLE
Could this compose file make an es cluster that distributed at different machine?

### ISSUE THREAD

**Issue by jevislee** [deviantony/docker-elk#503]
thanks

**Comment by antoineco** [comment]
Docker Compose always runs on a _single_ machine. You need a Swarm Cluster in order to scale across multiple nodes.

References:
* https://github.com/deviantony/docker-elk#swarm-mode
* https://github.com/deviantony/docker-elk#how-to-scale-out-the-elasticsearch-cluster
* https://docs.docker.com/compose/production/#running-compose-on-a-single-server
* https://docs.docker.com/compose/production/#running-compose-on-a-swarm-cluster

**Comment by jevislee** [comment]
thanks a lot,very appreciate your answer
