### ISSUE TITLE
how to save source ip and do not change that

### ISSUE THREAD

**Issue by b3nam** [deviantony/docker-elk#523]
hi guys
i've a problem with docker-compose version 3.8.
i want do not change source ip when i am using docker swarm.
are you have a idea?
for security concept , i want really source ip without changing.
thx

**Comment by antoineco** [comment]
Hi @b3nam, I'm kindly redirecting you to https://forums.docker.com/ and StackExchange for questions related purely to Docker products. Our work is on the integration of the _Elastic stack_ using Compose. Things like tweaking Docker products for deployments in specific environments is out of scope, otherwise we would have to support an entire community on all kind of unrelated problems.

Thank you for your understanding.
