### ISSUE TITLE
Do you usually force push in master branch?

### ISSUE THREAD

**Issue by PMExtra** [deviantony/docker-elk#546]
Recently, I found twice commit history changes in master branch, it caused my repository mirroring failed. (I'm mirroring this project to our internal git server)

I think we should try to avoid changing the history on public branches, right?

**Comment by antoineco** [comment]
It isn't usual on `master`, no, but it happened twice these past few days due to a lot of changes in the CI pipeline. We moved from Travis to GitHub Actions and I used force-push to fix some post-merge goof. Sorry for that! 

All changes are now in and the pipeline will run on every PR, so you shouldn't see any force push on `master` in the future.

**Comment by PMExtra** [comment]
OK, thanks for your work. This project helped us so much.
