### ISSUE TITLE
Sense Query fails

### ISSUE THREAD

**Issue by bbredenkamp** [deviantony/docker-elk#58]
I worked through the instructions.

I can call cURL: 
```
$ curl -XGET "http://localhost:9200/_cluster/health"
```

```
{"cluster_name":"elasticsearch","status":"yellow","timed_out":false,"number_of_nodes":1,"number_of_data_nodes":1,"active_primary_shards":6,"active_shards":6,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":6,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":50.0}
```

but the same command in sense fails:

url: http://localhost:5601/app/sense
server: http://localhost:9200/

response: 
```
Error connecting to 'http://localhost:9200/_search':

Client request error: connect ECONNREFUSED 127.0.0.1:9200
```

What am I missing?

**Comment by deviantony** [comment]
As written in the README:

> NOTE: In order to use Sense, you'll need to query the IP address associated to your network device instead of localhost.

You cannot query `localhost:9200` for the simple reason that Sense is installed in the Kibana container and that `localhost` in this containers resolves to the container itself.

In order to access your Elasticsearch instance via Sense, either query it via `http://elasticsearch:9200` (which is the Elasticsearch service name defined in the `docker-compose.yml` file) or use the IP address associated to your network device (e.g. `http://192.168.2.77:9200` for example).

**Comment by bbredenkamp** [comment]
...

Thank you.

Ben

**Comment by deviantony** [comment]
Noproblemo!
