### ISSUE TITLE
How to deploy these docker containers to AWS?

### ISSUE THREAD

**Issue by alex-dolbik** [deviantony/docker-elk#585]
I try to deploy this docker container to AWS ECS.
I created context and then I tried to do `docker compose up` and get an error `invalid reference format`.
What can be wrong here?

**Comment by antoineco** [comment]
@alex-dolbik possibly because all services have a `build` directive which requires images to be built locally:

https://github.com/deviantony/docker-elk/blob/37dc3c1d4a63a7f6f09815e426d6cfd29a71a2a7/docker-compose.yml#L5-L6

It could be that ECS doesn't support that, but we need it in this project to allow people to built images with custom plugins.

We have an alternative tailored for deployments to Docker's Swarm mode: https://github.com/deviantony/docker-elk/blob/main/docker-stack.yml. This one doesn't require building any image, it simply references Elastic's official images.
Maybe you'd have more luck deploying using this stack version.

I have never tried this myself, but please let us know how it goes!

**Comment by alex-dolbik** [comment]
No, it doesn't work this way too. So I just run docker on EC2 instance for now

**Comment by antoineco** [comment]
@alex-dolbik could you please share the error you encountered? Maybe we can make the required changes knowing what is going on, and this could also help others.

**Comment by shawnstrickland** [comment]
I'm trying to run docker compose with an AWS context in order to deploy to AWS from docker.

`level=warning msg="services.build: unsupported attribute"
service logstash doesn't define a Docker image to run: incompatible attribute`

Is the error I get when trying to run `docker compose up` from the root of the project using a context created from an AWS profile.

This occurred after trying to run a docker compose build (in default context) and adjusting the images under `build:` for each service type in docker-compose.yml

**Comment by antoineco** [comment]
@shawnstrickland to run the stack in a remote context you need to

1. replace all `build:` blocks with `image:` and set explicit image values (e g. "docker.elastic.co/elasticsearch/elasticsearch:8.0.1`)
2. remove all bind volumes, they will not work remotely since the files are on your local machine
3. pass the config values originally set in config files via environment variables instead

You can get an idea of how to do this by looking at Elastic:s demo Compose file: https://www.elastic.co/guide/en/elastic-stack-get-started/current/get-started-stack-docker.html#get-started-docker-tls

**Comment by shawnstrickland** [comment]
> @shawnstrickland to run the stack in a remote context you need to
> 
> 1. replace all `build:` blocks with `image:` and set explicit image values (e g. "docker.elastic.co/elasticsearch/elasticsearch:8.0.1`)
> 2. remove all bind volumes, they will not work remotely since the files are on your local machine
> 3. pass the config values originally set in config files via environment variables instead
> 
> You can get an idea of how to do this by looking at Elastic:s demo Compose file: https://www.elastic.co/guide/en/elastic-stack-get-started/current/get-started-stack-docker.html#get-started-docker-tls

Thanks for that info, I'll look into that!
