### ISSUE TITLE
Is it possible to create index lifecycle policy at start up time?

### ISSUE THREAD

**Issue by kevinyu0506** [deviantony/docker-elk#587]
I've managed to create **index template** by specifying the template in the logstash pipeline output and mount those template files into logstash container, is it possible for me to create **index lifecycle policy** at start up time as well?

**Comment by antoineco** [comment]
I don't think that's possible without some kind of automation on your side. The docs mention:

> You can create and manage index lifecycle policies through **Kibana Management** or the **ILM APIs**.
> -- *https://www.elastic.co/guide/en/elasticsearch/reference/current/index-lifecycle-management.html*

So my understanding is that you need to write something which pushes those policies to Elasticsearch upon the first boot.

Maybe you'll get more luck with that question at https://discuss.elastic.co/ though, because I have no experience with ILM at all and it's not something Docker can really solve for you.

**Comment by kevinyu0506** [comment]
Thanks for the quick response! I'll look into that.
