### ISSUE TITLE
elasticsearch overhead and exit

### ISSUE THREAD

**Issue by lifengmds** [deviantony/docker-elk#608]
Hi, 

Just a simple question so I would not post any config or error info here.

Every time I start all my containers (including elasticsearch, kibana,logstash), it consumes 100% 2 CPUs for several minutes, usually elasticsearch would not last very long even no tasks running and dead with overhead error. I have set the memory limit to 256M.  While I tried a clean stand alone version of elasticsearch, it works well. 

So I'm a little confused here. Is there any default tasks which are heavily loaded when start the container or how to use the minimum config for this package? 

Thanks you very much.

**Comment by antoineco** [comment]
@lifengmds Elasticsearch and Logstash are pretty resource intensive during the startup phase. It doesn't sound alarming to me that, together, they are using as much CPU as they can in order to start their routines.

However, if they keep using a lot of resources _after_ they are started, it could mean that you are receiving/processing more data than these default settings can handle. Keep in mind that 256MB is a **very** low default, and if Elasticsearch is starving on memory (or disk), the CPU will be waiting a lot as a result.

Do you have an estimation of how busy your stack is? (e.g. are you processing any input) Have you tried raising the heap to about 1GB?

**Comment by lifengmds** [comment]
Thanks very much for the remind. I tried to change configs several times, and it turns out it's a resource issue indeed.
