### ISSUE TITLE
Support for heartbeat?

### ISSUE THREAD

**Issue by matiwinnetou** [deviantony/docker-elk#672]
I see there are many extensions. Could it be possible to also add support for heartbeat?

https://www.elastic.co/guide/en/beats/heartbeat/current/running-on-docker.html

**Comment by antoineco** [comment]
@matiwinnetou I see you closed the issue, aren't you interested anymore?
The configuration would be fairly similar to the other Beats extensions present in the `extensions` directory, but we could add it if it helps.

**Comment by matiwinnetou** [comment]
Hi, I closed it yes because I am stupid, basically one can always install an app on the client side. For those people using docker on the client side I think it could be helpful indeed.

**Comment by antoineco** [comment]
Indeed, it is recommended to run client side, because running on the same machine as the stack will only allow monitoring the host that is running the stack.

If we add Heartbeat as an "extension", it is worth noting that the following lines will need to be deleted by the user in order to run as "standalone":

https://github.com/deviantony/docker-elk/blob/641290c20af46e995fa6ac7c8a0584b96b17c8a5/extensions/filebeat/filebeat-compose.yml#L29-L32

and the following host name won't resolve so it will need to be adjusted:

https://github.com/deviantony/docker-elk/blob/641290c20af46e995fa6ac7c8a0584b96b17c8a5/extensions/filebeat/config/filebeat.yml#L20-L21
