### ISSUE TITLE
`logstash_internal` user unauthorized on custom indices

### ISSUE THREAD

**Issue by pkral3** [deviantony/docker-elk#687]
The new logstash_internal user in configs cannot write on indices in runtime (v8.0.1):

> unauthorized for user [logstash_internal] with roles [logstash_writer] on indices

Solution: In ELK in Stack Management/Users assign to "logstash_internal" user the role as for "elastic" user

**Comment by antoineco** [comment]
@pkral3 thanks for reporting 👍

May I ask what indices you are writing to? The [default role](https://github.com/deviantony/docker-elk/blob/12dc0a4b74b2e983af36e4e2b04cead202427e85/setup/roles/logstash_writer.json) has permissions on the following indices:

- `logs-generic-default` (the data stream targeted by Logstash's default config)
- `logstash-*` (the index pattern when data streams are disabled in Logtash's config)
- `ecs-logstash-*` (the index pattern when data streams are disabled in Logtash's config _and_ ECS schema is enabled)
- logstash (alias used for managing index lifecycle)
- ecs-logstash (alias used for managing index lifecycle when ECS schema is enabled)

**Comment by pkral3** [comment]
Custom indices that were ok before logstash_internal are not writeable now. 
As an example in logstash/pipeline/logstash.conf define any esIndex

filter {
   if [app_id] == "process1" {
      grok {
       match => { "message" => "\[%{TIMESTAMP_ISO8601:logtimestamp}\] \[%{LOGLEVEL:loglevel}%{SPACE}\] \[%{GREEDYDATA:hostname}\] \[%{GREEDYDATA:environment}\] \[%{GREEDYDATA:project}\] \[%{GREEDYDATA:jobname}_%{GREEDYDATA:jobversion}\] \[%{GREEDYDATA:transaction}\] - %{GREEDYDATA:logmessage}" }
      }
      # create an elasticsearch index per month
      mutate { add_field => { "esIndex" => "process1-%{+YYYY.MM}" }}
    }
}

process1 index even existing from before with data in ELK, is not writeable with logstash_internal user (until it has not the role as elastic user has). It worked ok before, nok with 8.0.1 just with update.

**Comment by antoineco** [comment]
@pkral3 OK that's expected because `logstash_internal` is just assigned a **default** role during the initial stack startup (`logstash_writer`), but that role is only suitable for a fairly default log-oriented Logstash pipeline.

Obviously, we can not anticipate all the indices names that end users are going to target.
We can also not open the permissions to much because that would be quite unsecure, and we don't want to encourage people to use overprivileged users.

I can recommend a few options:
- Create another role via Kibana (e.g. `logstash_custom`) and assign it the [same permissions as the `logstash_writer` role](https://github.com/deviantony/docker-elk/blob/12dc0a4b74b2e983af36e4e2b04cead202427e85/setup/roles/logstash_writer.json), just with different indices names, based on your own Logstash config (e.g. `process1-*`).
- Edit the existing `logstash_writer` role created by docker-elk, and change/rename the indices patterns it contains.
- Give the `logstash_internal` user admin extended permissions, like you did, with the risk that this user can be abused to perform more changes than it is supposed to (e.g. perform modifications to the Elasticsearch cluster, read secrets, etc.)

**Comment by pkral3** [comment]
So there is no solution just to update, build and up -d as before now.

**Comment by antoineco** [comment]
Are you suggesting that we make `logstash_internal` a superadmin like before?
