### ISSUE TITLE
Cannot deploy the stack by docker-compose up

### ISSUE THREAD

**Issue by simwai** [deviantony/docker-elk#690]
### Problem description

Heyo, I tried to installl the docker-elk docker image with docker-compose up, but I just get that error:
ERROR: Invalid interpolation format for "environment" option in service "setup": "${KIBANA_SYSTEM_PASSWORD:-}"

#### Stack configuration

Freshly cloned repo

#### Docker setup

```console
$ docker version

Client: Docker Engine - Community
 Version:           20.10.13
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 10 14:07:52 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
```

```console
$ docker-compose version

docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.17
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
```

#### Container logs

```console
$ docker-compose logs

ERROR: Invalid interpolation format for "environment" option in service "setup": "${KIBANA_SYSTEM_PASSWORD:-}"
```

**Comment by antoineco** [comment]
@simwai thanks for the detailed report.

Does it work if you remove `:-` at the end of variable names? In other words, if just keep it like this: `${KIBANA_SYSTEM_PASSWORD}`

**Comment by simwai** [comment]
Heyo @antoineco, 

I've replaced now all :- in the docker-compose.yml file and get this error now. 

ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

Ty for your time and help.

**Comment by simwai** [comment]
@antoineco Yeah, I updated now docker-compose to latest version from pip instead of the latest 18.04 LTS apt-get version and now it works like a bless. Ty for being active on this awesome project.

**Comment by antoineco** [comment]
Glad it helped!

**Comment by KnightChaser** [comment]
It might be late, but I hope my comment is helpful to any people experiencing similar issues.

I was also building `docker-compose` of `docker-elk` in Ubutnu 18.04.6 LTS desktop(x64) and downloaded the `docker` and `docker-compose` packages with the available latest version. And I got the when I built the project via `sudo docker-compose up -d`(Well, `docker-compose version` showed the old version `1.17.1`, but I had no choice due to the old Ubuntu desktop release.), 
```
ERROR: Invalid interpolation format for "environment" option in service "kibana": "${:-KIBANA_SYSTEM_PASSWORD}"
```

1. Change the docker-compose file to `3.3`
2. Remove `init` and `profile` attributes in the `setup` part of `docker-compose`

```yml
version: '3.3'
services:
    ...
    setup:
        # profiles:
        #    -setup
       build:
             ...
       # init: true
       (cont'd)
```

I think using latest Ubuntu release is the most recommended solution for such Docker composing problems.
