### ISSUE TITLE
Changing the port for Kibana from 5601 to any thing but still the port used is 5601

### ISSUE THREAD

**Issue by rbcrack** [deviantony/docker-elk#691]
please see the screen shot 
![image](https://user-images.githubusercontent.com/18475926/158436294-ccf52e68-74df-4bba-bbeb-c467baabefef.png)

![image](https://user-images.githubusercontent.com/18475926/158436346-7cf385b9-6c5e-4d41-a827-d4132aa9b4b9.png)

![image](https://user-images.githubusercontent.com/18475926/158436391-362faa4a-a152-480b-a1dc-5816e3914f0b.png)

everything has started correctly but the issue is I cannot connect to Kibana

**Comment by antoineco** [comment]
@rbcrack the port you changed is the port exposed on your host by Docker, not the port of the Kibana server.
Change that value to `8622:5601` and Docker will properly forward your host's port `8622` to the port `5601` inside the container that runs Kibana.

To change the actual port Kibana is listening on, you need to edit the value of the `server.port` parameter inside Kibana's configuration. There are two ways to do this, both are explained in the README.
If you do that, don't forget to also edit the Compose file with `8622:<new port value>` so that Docker can forward to the right port.
