### ISSUE TITLE
No versioned releases or tags

### ISSUE THREAD

**Issue by qaxi** [deviantony/docker-elk#723]
### Problem description

No versioned releases or tags

As a CI/CD guy I would love to have some "marks" for point in code where developers feel it is ready to use for others.

Now I have to "minesweep" myself through SHA-1 hashes of full repo ...

When you have strict requirements on version for others, why not to show your versions?
(Docker Engine version 18.06.0 or newer, Docker Compose version 1.26.0 or newer )

**Comment by antoineco** [comment]
@qaxi I'm open to having a versioning scheme in place. The reason why we don't have any is because we have (at least) four uncorrelated variables that change over time in this project:

- The Elastic version (often)
- The version of Compose files (occasionally)
- Configuration files (rarely)
- Core, e.g. addition of the `setup` container after v8.0.0 release (very rarely)

I've been thinking about following the versioning scheme of Elastic, and adding increments between versions, such as `v8.2.1-001` or `v8.2.1-20220603` but the presence of a semantic version at the beginning may lead people into believing that docker-elk also follows semantic versioning, whereas it doesn't; `v8.2.1-001` and `v8.2.1-002` could be **non backwards compatible** due to changes to the required Docker or Compose version in between, for example.

What kind of versioning scheme do you suggest?
Like I said, I'm open to the idea.

**Comment by antoineco** [comment]
Actually, since Elastic versions have very little influence on the level of backward compatibility of the project (the same configuration files can likely be used throughout an entire Elastic release series like `v7.x.x` or `v8.x.x`), I suggest that we exclude the minor/patch Elastic version from our versioning scheme, and keep only the major version to reference the release series.

Something along those lines:

```
<elastic major>-<epoch>-<increment>
```

Examples, from earlier to newer:

```
7-2022.02-01
7-2022.02-02
8-2022.06-01
8-2022.07-01
```

We _may_ decide that every Elastic release also results in a new docker-elk release, but right now I don't think this should be a priority. I think other changes, such as config changes, modifications to scripts, etc. should be the main driver. Elastic versions can always be changed in the `.env` files, regardless of the docker-elk release.

So imagine we start versioning today at `8-2022.06-01` and the Elastic version is `8.2.2`.
If Elastic `8.3.0` gets released tomorrow, I would wait until the next change to docker-elk config/core files to release the next increment, which could either be `8-2022.06-02`, `8-2022.07-01` or something at an even later date if nothing significant changes in the repository.

What do you think?

**Comment by qaxi** [comment]
From my point of view, semantic versioning is the best option.
But if "rolling" updates without "minor/major feature" versions work for you, I can live with that.

I would just mention, that version string like "v8-2022.06-02" do not work well with some toolsets (version comparsion ...) . But "8.2022.06.2", "8.202206.2" or "8.15" works fine everywhere (now "v", no "-", no "leading 0")

**Comment by antoineco** [comment]
Semantic versioning is usually a sound option, I agree. In our case we have to be careful because the "revision" encompasses different uncorrelated things like I mentioned in my first comment, so it's hard to reason about releases as major/minor/patch.

Regarding the "v" prefix, I added it in my sample because of this: https://semver.org/#is-v123-a-semantic-version.
I'm fine dropping it, it's unlikely that we use tags for anything else than versioning after all (we haven't so far).

Regarding avoiding dashes and padding zeroes, I'm also fine with your suggestion.

**Comment by antoineco** [comment]
@qaxi I created three releases in the repo, check it out: https://github.com/deviantony/docker-elk/releases

```
8.2202.1
8.2203.1
8.2206.1
```

The pattern is `<elastic major>.<yymm>.<increment>`.
I think it fits well as a pseudo-semantic versioning scheme and should work well with any tool.

**Comment by qaxi** [comment]
Thank you, It will work for me perfectly.
