### ISSUE TITLE
Elastic Agent not delivering logs and metrics to elastic

### ISSUE THREAD

**Issue by SamTV12345** [deviantony/docker-elk#747]
So I followed the setup documentation, accessed kibana and started managing fleet. I can add elastic agents to the fleet, but they dont send any logs or metrics.

What I did:

1. git clone ...
2. cd into directory
3. docker-compose up -d
4. Log into Kibana with elastic changeme
5. Go to Management->Fleet
6. Install fleet server following the guide, it also connects with no problem
7. Add agents, following the shown commands, the agents also register at the server and I can change policies and roll them out but when clicking on logs I can't see anything

Am I doing something wrong or is this docker-compose stack not ready for elastic agents?

**Comment by antoineco** [comment]
@SamTV12345 I can't think about a reason for agents not to work properly with this stack, unless they are trying to communicate over a port that isn't exposed on the host.

Let me try to reproduce and I'll get back to you with (hopefully) a solution.

**Comment by SamTV12345** [comment]
Alright. Thanks for your help.

**Comment by antoineco** [comment]
@SamTV12345 looking into this today.

**Comment by antoineco** [comment]
@SamTV12345 I'm observing the same behavior. Agents register OK but don't send any data, for reasons I can't comprehend. I see no error whatsoever in the logs.

I've been following this guide for both the server and agents: https://www.elastic.co/guide/en/fleet/current/elastic-agent-container.html

**Comment by antoineco** [comment]
Actually, I found something in the agent's logs in `/usr/share/elastic-agent/state/data/logs/default/...`:

```json
{
  "log.level": "error",
  "@timestamp": "2022-08-11T21:21:25.836Z",
  "log.logger": "publisher_pipeline_output",
  "log.origin": {
    "file.name": "pipeline/client_worker.go",
    "file.line": 150
  },
  "message": "Failed to connect to backoff(elasticsearch(http://localhost:9200)): Get \"http://localhost:9200\": dial tcp 127.0.0.1:9200: connect: connection refused",
  "service.name": "filebeat",
  "ecs.version": "1.6.0"
}
```

It turns out that the default Fleet settings are wrong:

![image](https://user-images.githubusercontent.com/3299086/184248202-db6e0ded-a9b4-4675-8d52-b763eaad9c33.png)

After changing it to Elasticsearch's public URL and deploying the updated policies (fleet server + agents), data started flowing in:

![image](https://user-images.githubusercontent.com/3299086/184249280-381ecf07-a251-4a55-831f-a35f2d76e56e.png)

![image](https://user-images.githubusercontent.com/3299086/184249431-d61bb7a7-f3a3-4ed1-be5d-9b04f182c91f.png)

**Comment by SamTV12345** [comment]
Awesome. It works like a charm. Thank you for helping me. Maybe you could add these instructions to the README file?

**Comment by antoineco** [comment]
Yes while playing with Fleet yesterday (first time to be honest with you) I realized it could be useful to have a containerized Fleet "extension" with setup instructions in the repo.

It wouldn't be useful for running a real fleet of Elastic agents, because agents are meant to be deployed on real servers, but it could act as a good quick start for testing setups with third-party integrations, etc.

**Comment by antoineco** [comment]
This feature request is now being tracked in #749.
