### ISSUE TITLE
do not have permission to access the requested page

### ISSUE THREAD

**Issue by ljs528** [deviantony/docker-elk#748]
When I visited Kibana after the server was successfully started, I was prompted that I had no permission to log in. The user who logged in was Kibana_system. May I ask what caused this problem?
![image](https://user-images.githubusercontent.com/41655351/183319821-5e78aad9-7495-4dd8-8b65-3df29e69721e.png)
The service is started and 'Kibana.yml' is configured with 'server.host 0.0.0.0'
![image](https://user-images.githubusercontent.com/41655351/183319810-8d7a4728-16ad-44ca-bc60-5978831c73e1.png)
![image](https://user-images.githubusercontent.com/41655351/183322613-0b3bee1e-0bbb-4cb7-aee2-bf9b6b887562.png)

**Comment by ljs528** [comment]
8/5000 
I see what the problem is, okay

**Comment by antoineco** [comment]
@ljs528 glad you figured what the problem was.

For other people reading this: the `kibana_system` user is a **system** user that is only meant to be used by Kibana's _backend_.
People connecting via the Kibana web application (frontend) should use a user with at least `read` permissions on Elastic settings and indices. The recommendation is to start with the `elastic` super-user, then [create users with lower privileges](https://www.elastic.co/guide/en/kibana/current/tutorial-secure-access-to-kibana.html) for people to connect via Kibana.
