### ISSUE TITLE
Add elastic apm configuration

### ISSUE THREAD

**Issue by SamTV12345** [deviantony/docker-elk#756]
### Problem description

I am stuck at configuring elastic with the apm server. I setup a fleet server. Do I need another service for the apm server or is this integrated in the fleet server? Maybe you could add a section for setting an apm server up and adding agents to it.

### Steps done

Add the elastic apm integration. Point the urls to the fleet url.

In the apm agent I am getting the log  output that: 
2022-09-01 22:24:42,564 [elastic-apm-server-reporter] WARN  co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - It seems like you are using a version of the APM Server which is not compatible with this agent. Please use APM Server 6.5.0 or newer.

so it could be that I really need another server.

**Comment by antoineco** [comment]
You're right, Fleet integration is on my priority list (#749), unfortunately I haven't had the time to write a working sample with docs yet.
At the same time, I just realized the APM integration we currently have in the repo (extensions/apm-server) was being deprecated, so that gives me even more motivation to work on that rather soon.

I was just reading [apm-quick-start.html](https://www.elastic.co/guide/en/apm/guide/8.4/apm-quick-start.html#add-apm-integration) and it looks like Elastic Agents embed a **local APM server** that can collect APM data from apps running on that host. Neat!
This means that you'll most likely want to [keep `localhost:8200` as the default host and port](https://www.elastic.co/guide/en/apm/guide/current/input-apm.html) while enabling the Elastic APM integration (step 2), because _each_ agent exposes its own local endpoint in such setup.

> **Note**
> One exception: if agents run as Docker containers and don't share the host's network, set this to `0.0.0.0:8200` to allow listening on the container's interface.
> Probably not a great practice because then agents monitor the container instead of the host... but maybe you just want to prototype something.

Then you'll need to deploy an Elastic Agent onto the host that's running your application (step 3), with the policy that you configured in step 2. At that stage your agent should be:

- collecting metrics
- collecting logs
- exposing a **local** APM server on `localhost:8200` ⭐

Finally, follow step 4 — which is language specific — and omit the configuration of the APM server URL. It will default to `localhost:9209`, which is correct since your local agent is handling APM data (and sending it automatically to the Fleet server for consumption via Kibana).

**Comment by SamTV12345** [comment]
Thank you for your guide. I managed to deploy the elastic agent, set the integrated apm server to listen to 0.0.0.0:8200 and the result is astonishing. 

I can see every stacktrace in my Java app, every trace to the database and other services and cpu usage of the proxmox lxc. The only thing I am missing are the logs of the app. Concerning the last problem with localhost:8200 that didn't work as the java app is itself contained in a docker container. So I need to find a way to pass environment variables to that container.

**Comment by antoineco** [comment]
Merging with #749.
Since APM is now part of Elastic Agent, APM-specific aspects will be addressed together with the Fleet extension.
