### ISSUE TITLE
The fleet container exits before Kibana has fully started

### ISSUE THREAD

**Issue by pedroaugustofsilva** [deviantony/docker-elk#763]
Hello!

The fleet doesn't go up with the [fleet's README command](https://github.com/deviantony/docker-elk/blob/main/extensions/fleet/README.md#usage):

`$ docker-compose -f docker-compose.yml -f extensions/fleet/fleet-compose.yml up`

I won't add more information because I don't think the problem is related to the context. I just cloned the project and made no further changes to it.

Currently, I added `restart: unless-stopped` in the container configuration. I don't think is the best solution.

Maybe write a custom entrypoint for the fleet container?

**Comment by antoineco** [comment]
Maybe it's related to that note in the README?

> Elastic Agent does not retry failed connections to Kibana upon the initial enrollment phase. Therefore, Kibana must be fully started before this extension can be run.

An automatic restart could be one way to motivate that issue until Elastic addresses it indeed.

**Comment by antoineco** [comment]
The issue with a custom entrypoint is that it can get rapidly very hacky. I don't think that simply waiting for any response from Kibana's URL would be sufficient because the server is responsive before its dependencies are (could be wrong, I need to double check). If that is the case, it needs API calls from the script need to be authenticated.

Elastic Agent has multiple ways to obtain credentials to authenticate with Kibana: environment variables, config file, tokens... Handling all these requires something quite sophisticated for a "wait script", especially considering this extension is still considered experimental.

I think it's time to bring up the issue with Elastic, especially since their other products _are_ resilient to non-ready dependencies.
