### ISSUE TITLE
Setup container times out while creating users

### ISSUE THREAD

**Issue by maw2be** [deviantony/docker-elk#767]
### Problem description

I pull files from git. follow instruction. Start with docker-compose up -d 
On kibana in logs I see:
[ERROR][elasticsearch-service] Unable to retrieve version information from Elasticsearch nodes. security_exception: [security_exception] Reason: unable to authenticate user [kibana_system] for REST request [/_nodes?filter_path=nodes.*.version%2Cnodes.*.http.publish_address%2Cnodes.*.ip]

On logstash in logs I see:
logstash.outputs.elasticsearch][main] Attempted to resurrect connection to dead ES instance, but got an error {:url=>"http://logstash_internal:xxxxxx@elasticsearch:9200/", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError, :message=>"Got response code '401' contacting Elasticsearch at URL 'http://elasticsearch:9200/'"}

**Comment by antoineco** [comment]
Could you please share the output of `docker-compose logs setup`?

(We explicitly ask in the issue template to share all logs to avoid these unnecessary questions.)

**Comment by maw2be** [comment]
container is called docker-elk_setup_1 as I'm using Linux
-------- Thu Oct 13 18:21:21 UTC 2022 --------[+] Waiting for availability of Elasticsearch. This can take several minutes.   ⠿ Elasticsearch is running
[+] Role 'logstash_writer'
   ⠿ Creating/updating

**Comment by antoineco** [comment]
(You don't need the container name. Compose takes a service name, not a container name, just copy and paste the command I shared. Works on any platform.)

The setup service is stuck creating the user it seems.

Please run `docker-compose up setup` (EXACTLY this command) and wait about 5min, even if nothing is printed on the screen. The setup should eventually fail, I want to see the error.

**Comment by maw2be** [comment]
-------- Thu Oct 13 18:36:13 UTC 2022 --------[+] Waiting for availability of Elasticsearch. This can take several minutes.   ⠿ Elasticsearch is running[+] Role 'logstash_writer'   ⠿ Creating/updating

exit status 28

**Comment by antoineco** [comment]
If connections to Elasticsearch time out at that stage in the process, it means that Elasticsearch is unhealthy.
Again, you didn't share your logs so that's the best I can tell you.

Check your Elasticsearch logs, the answer will be there. Maybe you don't have enough disk space available, or some index is corrupted, or it runs out of heap space, ...

**Comment by maw2be** [comment]
This is log from elastic container, as you see it's big 
I have around 10GB of free space (not saw any information about low space), heap space is ok as using for java development and don't have issues. I try to setup apm and logstash to better monitor my app.

In past I was running this deployment before SETUP was introduced without issues.
this part about kibana_system is going and going....
[15129a2c6a8005062d7907ffb4acde85b00f339d1fd1e82143c2614245abf250-json.log](https://github.com/deviantony/docker-elk/files/9780297/15129a2c6a8005062d7907ffb4acde85b00f339d1fd1e82143c2614245abf250-json.log)

**Comment by antoineco** [comment]
Setup was introduced because the `kibana_system` user needs to be set up explicitly since Elastic v8, it's not possible to use the `elastic` user in the Kibana config anymore, so this new init step is unfortunately necessary.

It seems like you upgraded from an old Elastic v7 stack, possibly without following a clean upgrade path, and your shards are now corrupted/unavailable:

```
at least one primary shard for the index [.security-7] is unavailable
```

That's why the setup is unable to proceed, and why your stack is in limbo.

If you don't have any important data in Elasticsearch and are OK with starting fresh, the easiest way to recover is to wipe the stack's data with:

```
docker-compose down -v
```

("-v" for "volumes")

After that, `up` the stack again and pay attention to the logs of the setup container. Once it has completed, Kibana will start its own initialization cycle.

**Comment by maw2be** [comment]
I've solve this issue with
sudo sysctl -w vm.max_map_count=262144
but I have couple other issues.
I fix them be clearing space on my disk to 40GB 
You can add this information (about vm.max and disk space required) to readme file.

**Comment by antoineco** [comment]
Glad you figured something out.
