### ISSUE TITLE
APM server extension

### ISSUE THREAD

**Issue by jvmlet** [deviantony/docker-elk#773]
One of the recent PR removed `apm-server` in favor of `fleet-server`, but this also means that open telemetry support is dropped, if I'm not mistaken. If this is indeed true, would you please bring `apm-server` back ?

**Comment by jvmlet** [comment]
Thanks for the answer, does it mean that `fleet-server` is acting like `apm-server` if `8200` is exposed  ?

**Comment by jvmlet** [comment]
[This guide](https://www.elastic.co/guide/en/apm/guide/8.4/open-telemetry.html) still advises to install `apm-server`

**Comment by antoineco** [comment]
> does it mean that `fleet-server` is acting like `apm-server` if `8200` is exposed ?

Yes and no.
To be more precise, APM Server — when installed as an Elastic Integration as described in [Step 2: Configure the APM integration (Self-Managed)](https://www.elastic.co/guide/en/apm/guide/8.4/apm-quick-start.html#add-apm-integration) — is running _alongside_ Fleet Server, inside the same container.

In fact, you can also run the two separately. All you need is a container with an Elastic Agent (Fleet Server _is_ an Elastic Agent itself!) so that APM Server can be installed using the new procedure (via Kibana, _Step 2 ..._).

> [This guide](https://www.elastic.co/guide/en/apm/guide/8.4/open-telemetry.html) still advises to install `apm-server`

Of course, APM Server still needs to be installed, it's just that the installation procedure is now different (see above).
Instead of being a standalone piece of software, APM Server is now part of Elastic Agent. Under the hood, it's still the same software, Elastic is just pushing to have all its satellite agents managed in a central location.

**Comment by antoineco** [comment]
Just to illustrate my previous comment, here is me installing the APM Server through Kibana:

![image](https://user-images.githubusercontent.com/3299086/197562222-2c7d82ff-f2e9-4880-868a-27b7491a344a.png)

![image](https://user-images.githubusercontent.com/3299086/197562331-81ed7644-c584-4f89-8015-b2eb16e45950.png)

When I inspect what's running inside the Fleet Server container, I can now see the APM Server alongside other agents such as Filebeat, Metricsbeat, Fleet, ...

```console
$ docker container exec docker-elk-fleet-server-1 ps 
    PID TTY          TIME CMD
      1 ?        00:00:00 tini
      7 ?        00:00:09 elastic-agent
     46 ?        00:00:01 fleet-server
    115 ?        00:00:00 apm-server
    124 ?        00:00:00 metricbeat
    134 ?        00:00:00 filebeat
    142 ?        00:00:00 filebeat
    151 ?        00:00:00 metricbeat
    204 ?        00:00:00 ps
```

I can also see both `fleet-server` and `apm-server` listening on their respective TCP ports:

```console
$ docker container exec -u root docker-elk-fleet-server-1 apt -y -q install iproute2
```

```console
$ docker container exec docker-elk-fleet-server-1 ss -tlpn
State     Recv-Q    Send-Q   Local Address:Port   Peer Address:Port  Process
LISTEN    0         128          127.0.0.1:8221        0.0.0.0:*      users:(("fleet-server",pid=46,fd=17))
LISTEN    0         128          127.0.0.1:6789        0.0.0.0:*      users:(("elastic-agent",pid=7,fd=11))
LISTEN    0         128         127.0.0.11:44313       0.0.0.0:*
LISTEN    0         128                  *:8220              *:*      users:(("fleet-server",pid=46,fd=16))
LISTEN    0         128                  *:8200              *:*      users:(("apm-server",pid=115,fd=11))
```

**Comment by jvmlet** [comment]
Thanks a lot @antoineco

**Comment by irontoby** [comment]
Thanks @antoineco for the explanations on this.

For anyone like me who's a bit confused at things getting moved around / renamed / integrated into Fleet, and you're just trying to run the ELK stack and Fleet / APM integrations on a single machine so that port 8200 is available for APM clients to connect to, you need to run the following:

```
docker compose -f docker-compose.yml -f extensions/fleet/fleet-compose.yml -f extensions/fleet/agent-apmserver-compose.yml up -d
```

If you already have just the "base" system running via the main `docker-compose.yml`, you can still just run the above command and it will start the other containers alongside it.

**Comment by antoineco** [comment]
I agree, we should definitely make that command more obvious in the documentation.

Right now it's hidden inside the Compose file used as example:

https://github.com/deviantony/docker-elk/blob/7e965bb33f09c1f320a647d8440b8bcf4d88bf3e/extensions/fleet/agent-apmserver-compose.yml#L6-L11

**Comment by antoineco** [comment]
/
