### ISSUE TITLE
Docker compose up setup not working since release 8.2305.1

### ISSUE THREAD

**Issue by tigerblue77** [deviantony/docker-elk#874]
Just wget the release archive, unzip or untar it then :
```
root@Ultron:~/docker-elk# docker-compose up setup
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.setup: 'profiles'
```

**Comment by antoineco** [comment]
I assume this is because you are using an old Compose version:

> The minimum Compose version requirement was increased to `1.28.0`.
>
> -- https://github.com/deviantony/docker-elk/releases/tag/8.2305.1

As an additional note, downloading the code as a Zip file might cause the executable flag of shell scripts to be removed/ignored, so `docker-compose up setup` might not work until the executable flag is restored with `chmod +x setup/entrypoint.sh`.

**Comment by tigerblue77** [comment]
I missed that, I'm in 1.25.0. Thank you !

**Comment by antoineco** [comment]
You can still get docker-elk running fairly easily with Compose 1.25.0 with minor modifications, such as moving the `setup` service to a separate Compose file, and include that file only on the first stack startup.
