### ISSUE TITLE
docker-elk works great, how to integrate other systems filebeat/metricbeat

### ISSUE THREAD

**Issue by lcia-projects** [deviantony/docker-elk#881]
i've got docker-elk working great on a ubuntu server. 

i'd like to setup filebeat, metricbeat, and heartbeat on other servers on my network to send data to the docker-elk instance i have set up to help monitor all my other servesr. 

whats the best way to do that? 

would i just run the extensions and not the main docker-compose? 

how would i set the servername for metricbeat, filebeat, and heartbeat? is there an environmental variable?

**Comment by antoineco** [comment]
I don't recommend using the extensions as-is for running "the Beats". They are preconfigured for running within the same Compose stack as the main components, so you would have to perform the following modifications:

- Remove `depends_on`
- Change the network
- Update URLs to use external (host)names instead of internal Compose names
- Copy TLS certificates over to your agents

IMO Compose makes sense for running related applications together, but not so much for standalone services (although it is absolutely possible to do so).

Instead, I recommend following whichever method is either recommended in Elastic's documentation, or common for other applications in your environment (OS packages/services, bare Docker, ...). You would still need to change the things I mentioned, but at least you would be free to orchestrate it the way you please across multiple machines.

All or this is very general advice of course 🙂

**Comment by lcia-projects** [comment]
thank you, thats the same conclusion i came to.. i was just hoping there was a simpler approach i hadnt thought of.
