### ISSUE TITLE
Kibana Login Problem

### ISSUE THREAD

**Issue by Mertozturkk** [deviantony/docker-elk#952]
I followed the steps you explained in Readme. I reset the passwords, but when I log in to Kibana with the elastic user, the page refreshes without any errors and the same place opens again. What could be the problem?

#### Docker setup
```console
$ docker version

Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:08:01 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:08:01 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.26
  GitCommit:        3dd1e886e55dd695541fdcd67420c2888645a495
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

```console


$ docker-compose version

docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Comment by antoineco** [comment]
Was the issue closed on purpose?

**Comment by Mertozturkk** [comment]
Yes, I'm sorry to bother you, I would have left it simple. It didn't work after a few tries, so I wanted to ask you, but I fixed it later. It was a browser problem

**Comment by pkExec** [comment]
For anyone else that encounters this, I had the same problem when opening the login page via IP instead of hostname. 

Chrome displays following error:
":5601/login?next=%2F:1 The Cross-Origin-Opener-Policy header has been ignored, because the URL's origin was untrustworthy. It was defined either in the final response or a redirect. Please deliver the response using the HTTPS protocol. You can also use the 'localhost' origin instead. See https://www.w3.org/TR/powerful-features/#potentially-trustworthy-origin and https://html.spec.whatwg.org/#the-cross-origin-opener-policy-header."

Edge is happy to ignore it (for now) and proceeds normally.
