### ISSUE TITLE
Data persistence in swarm (Wiki)

### ISSUE THREAD

**Issue by nmathew98** [deviantony/docker-elk#991]
there is a section in the wiki about data persistence when scaling out the elastic cluster: https://github.com/deviantony/docker-elk/wiki/Elasticsearch-cluster#data-persistence

in Elastic v8 onwards, the way to do it is to set the `path.data` configuration as part of env vars: https://www.elastic.co/guide/en/elasticsearch/reference/current/important-settings.html#path-settings

in docker swarm, this would be like so:

<img width="619" alt="image" src="https://github.com/deviantony/docker-elk/assets/55116576/b41e00de-b483-4d97-bc4d-0de196d2a8f2">

`path.data` configuration: https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html#data-path

**Comment by antoineco** [comment]
Thanks for the hint! If you feel like contributing that change the wiki can be edited by anyone. Otherwise I'll do it sometime next week.

**Comment by antoineco** [comment]
We had a request to add this once as part of
- #859

In my opinion deployment concerns are out-of-scope for docker-elk. There are a lot of ways to expose web applications securely over a network, and we are better off staying away from opinionated recommendations in this project, especially since the main focus is on single-host deployments via Docker Compose.
The instructions for Swarm are a leftover from a time where we did have a Swarm configuration in the project, but this configuration didn't fit very well into the project. I left the instructions in the wiki nevertheless, for educational purposes.

**Comment by nmathew98** [comment]
wiki's been updated

**Comment by antoineco** [comment]
Thank you for your contribution, much appreciated!
